// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANzZWOX-rZ_c790IWDsYu7WXuHhfmyQBA',
    appId: '1:626925638616:web:0ed490845bf5a3101158ad',
    messagingSenderId: '626925638616',
    projectId: 'chatapp-bijog',
    authDomain: 'chatapp-bijog.firebaseapp.com',
    storageBucket: 'chatapp-bijog.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnLsCleTG5rd2GIcGpfS2IfNcpHxZQBmc',
    appId: '1:626925638616:android:9ce895819e249a9b1158ad',
    messagingSenderId: '626925638616',
    projectId: 'chatapp-bijog',
    storageBucket: 'chatapp-bijog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAetfxx-JlIM-FmTitS0aZL9n4P8PvHqYU',
    appId: '1:626925638616:ios:379b127c8a23737e1158ad',
    messagingSenderId: '626925638616',
    projectId: 'chatapp-bijog',
    storageBucket: 'chatapp-bijog.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAetfxx-JlIM-FmTitS0aZL9n4P8PvHqYU',
    appId: '1:626925638616:ios:379b127c8a23737e1158ad',
    messagingSenderId: '626925638616',
    projectId: 'chatapp-bijog',
    storageBucket: 'chatapp-bijog.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANzZWOX-rZ_c790IWDsYu7WXuHhfmyQBA',
    appId: '1:626925638616:web:36233c21dd80175e1158ad',
    messagingSenderId: '626925638616',
    projectId: 'chatapp-bijog',
    authDomain: 'chatapp-bijog.firebaseapp.com',
    storageBucket: 'chatapp-bijog.firebasestorage.app',
  );
}
